name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: lab3 test
      id: lab3-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: lab3 test
        setup-command: ./gradlew build
        command: ./gradlew test
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LAB3-TEST_RESULTS: "${{steps.lab3-test.outputs.result}}"
      with:
        runners: lab3-test
